import { Outfit } from "next/font/google";
import { Metadata } from "next";
import { Providers } from "../providers";
import { ReactNode } from "react";
import { AuthRedirect } from "@/lib/protectRoute";
import "../globals.css";

const outfit = Outfit({
    variable: "--font-outfit",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "WiseWaste",
    description: "Generated by create next app",
};

export default function AuthLayout({ children }: { children: ReactNode }) {
    return (
        <html lang="en">
            <body className={`${outfit} antialiased`}>
                <Providers>
                    <AuthRedirect>
                        {children}
                    </AuthRedirect>
                </Providers>
            </body>
        </html>
    );
}
