import { Outfit } from "next/font/google";
import "../globals.css";
import { Metadata } from "next";
import { Providers } from "../providers";

const outfit = Outfit({
    variable: "--font-outfit",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "WiseWaste",
    description: "Generated by create next app",
};

export default function AuthLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body className={`${outfit} antialiased`}>
                <Providers>
                    {children}
                </Providers>
            </body>
        </html>
    );
}
