import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import { Providers } from "../providers";
import { Navbar } from "@/layout/Navbar";
import { Footer } from "@/layout/Footer";
import { AuthRedirect } from "@/lib/protectRoute";
import "../../app/globals.css";

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "WiseWaste",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={`${outfit} antialiased`}>
        <Providers>
          <AuthRedirect>
            <Navbar />
            {children}
            <Footer />
          </AuthRedirect>
        </Providers>
      </body>
    </html>
  );
}
