import { Outfit } from "next/font/google";
import { Metadata } from "next";
import { Providers } from "../providers";
import { ReactNode } from "react";
import "../globals.css";
import Sidebar from "@/layout/Sidebar";

const outfit = Outfit({
    variable: "--font-outfit",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "WiseWaste",
    description: "Generated by create next app",
};

export default function AdminLayout({ children }: { children: ReactNode }) {
    return (
        <html lang="en">
            <body className={`${outfit.variable} antialiased`}>
                <Providers>
                    <div className="flex flex-col min-h-screen">
                        <div className="flex flex-1">
                            <Sidebar role="admin" />
                            <main className="flex-grow ml-[270px] overflow-y-auto p-4">
                                {children}
                            </main>
                        </div>
                    </div>
                </Providers>
            </body>
        </html>
    );
}