import { Outfit } from "next/font/google";
import { Metadata } from "next";
import { Providers } from "../providers";
import { ReactNode } from "react";
import { SessionProvider } from "next-auth/react";
import "../globals.css";
import Sidebar from "@/layout/Sidebar";
import UserDetail from "@/components/server/UserDetail";
import { AdminRequired } from "@/lib/protectRoute";

const outfit = Outfit({
    variable: "--font-outfit",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "WiseWaste",
    description: "Generated by create next app",
};

export default function AdminLayout({ children }: { children: ReactNode }) {
    return (
        <html lang="en">
            <body className={`${outfit.variable} antialiased`}>
                <SessionProvider>
                    <Providers>
                        <AdminRequired>
                            <div className="flex min-h-screen">
                                <Sidebar role="admin" userDetails={<UserDetail />} />
                                <div className="flex-1 ml-64">
                                    {children}
                                </div>
                            </div>
                        </AdminRequired>
                    </Providers>
                </SessionProvider>
            </body >
        </html >
    );
}