import { Outfit } from "next/font/google";
import { Metadata } from "next";
import { Providers } from "../providers";
import { ReactNode } from "react";
import "../globals.css";
import Sidebar from "@/layout/Sidebar";
import UserDetail from "@/components/server/UserDetail";

const outfit = Outfit({
    variable: "--font-outfit",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "WiseWaste",
    description: "Generated by create next app",
};

export default function ResidentLayout({ children }: { children: ReactNode }) {
    return (
        <html lang="en">
            <body className={`${outfit.variable} antialiased`}>
                <Providers>
                    <Sidebar role="resident" userDetails={<UserDetail />} />
                    {children}
                </Providers>
            </body>
        </html>
    );
}